Implements command pencil
rastrr-editor/core pull request #18
Opened 2022-12-23 14:52 UTC by hunteraf87

2022-12-23 16:08 UTC, shining-mind requested changes

2022-12-23 16:08 UTC, shining-mind commented on src/commands/layer-command.ts
> +  protected iterator: AsyncIterableIterator<Rastrr.Point>;
тип стоит указать AsyncIterable не зачем указывать ещё и Iterator - это избыточно.

2022-12-23 16:08 UTC, shining-mind commented on src/commands/pencil-command.ts
> +
beginPath имеет смысл вызвать до цикла.

2022-12-23 16:18 UTC, shining-mind commented on src/commands/pencil-command.ts
> +export default class PencilCommand extends LayerCommand implements Command {
Должна быть возможность указать:
- [цвет](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/strokeStyle)
- [ширину линии](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineWidth)
- [форму окончания линии](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/lineCap)
- [непрозрачность](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/globalAlpha) либо можно использовать [rgba в strokeStyle](https://stackoverflow.com/questions/9231531/transparency-of-a-filled-stroke-in-html5)

2022-12-23 16:35 UTC, shining-mind commented on src/commands/pencil-command.ts
> +        this.context.stroke();
важно учитывать, что stroke будет прорисовать [заново все пути](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/stroke#re-stroking_paths) нарисованные с момента вызова `beginPath` возможно имеет смысл начинать новый путь для каждой точки

2022-12-23 16:36 UTC, shining-mind commented on src/commands/pencil-command.ts
> +        this.context.stroke();
однако не факт, что это будет более производительно, тут надо потестировать

2022-12-23 21:36 UTC, hunteraf87 commented on src/commands/pencil-command.ts
> +export default class PencilCommand extends LayerCommand implements Command {
strokeStyle ведет себя не очень хорошо с прозрачностью. Возможно придется вообще переделывать механизм для кисти.

2022-12-23 21:37 UTC, hunteraf87 commented on src/commands/pencil-command.ts
> +        this.context.stroke();
Попробовал создавать каждый раз новый путь, но чего то особенного не увидел. Поэтому пока оставил старый вариант т.к меньше кода. Переделать проблем не будет.

2022-12-24 05:55 UTC, shining-mind commented on src/commands/pencil-command.ts
> +export default class PencilCommand extends LayerCommand implements Command {
думаю тут нужен globalAlpha всё-таки

2022-12-24 05:55 UTC, shining-mind commented on src/commands/pencil-command.ts
> +        this.context.stroke();
Ок

2022-12-24 06:04 UTC, shining-mind requested changes

2022-12-24 06:04 UTC, shining-mind commented on src/color/color.ts
> +  toCssStyle(): string {
Ещё нужен статический метод from [по аналогии с Buffer](https://nodejs.org/api/buffer.html#static-method-bufferfromstring-encoding), который на вход принимает строку и тип

2022-12-24 06:04 UTC, shining-mind commented on src/commands/brush-command.ts
> +    iterator: AsyncIterable<Rastrr.Point>,
аргумент стоит назвать iterable

2022-12-24 06:04 UTC, shining-mind commented on src/commands/brush-command.ts
> +    this.context.strokeStyle = this.options.color.toCssStyle();
пробуем сделать через [globalAlpha ](https://developer.mozilla.org/ru/docs/Web/API/CanvasRenderingContext2D/globalAlpha)- я почитал, что трюк с rgba вроде не работает в новых версиях браузеров

2022-12-24 06:04 UTC, shining-mind commented on src/commands/brush-command.ts
> +    this.context.closePath();
Этот метод рисует [прямую линию между началом и концом пути](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/closePath), ты в своем тесте не увидел проблемы, потому что у тебя путь - это прямая линия, но если нарисовать полукруг то его концы будут соединены - это не совсем то, что нам нужно

2022-12-24 06:04 UTC, shining-mind commented on src/commands/layer-command.ts
> +  constructor(layer: Layer, iterator: AsyncIterable<Rastrr.Point>) {
iterator -> iterable

2022-12-24 10:45 UTC, hunteraf87 commented on src/commands/pencil-command.ts
> +export default class PencilCommand extends LayerCommand implements Command {
globalAlpha это для всего слоя выставляется

2022-12-24 12:04 UTC, merged