Implements rectangle command
rastrr-editor/core pull request #25
Opened 2022-12-27 19:02 UTC by hunteraf87

2022-12-28 07:34 UTC, shining-mind requested changes

2022-12-28 07:34 UTC, shining-mind commented on src/commands/layer-commands/rect-command.ts
> +  constructor(
Очень много повторяющегося кода с командой Brush, надо пожалуй создать промежуточный абстрактный класс в который вынести повторяющийся код.

2022-12-28 08:40 UTC, coderNeos commented on src/commands/layer-commands/rect-command.ts
> +  constructor(
И самое главное rect-command должен расширять ShapeCommand. Т.к. каждая фигура производит новый слой (аналогично тому как это работает в photoshop)

2022-12-28 19:11 UTC, shining-mind requested changes

2022-12-28 19:11 UTC, shining-mind commented on src/commands/layer-command.ts
> -export default class LayerCommand {
А почему все удалено?

2022-12-28 19:11 UTC, shining-mind commented on src/commands/layer-command.ts
> -export default class LayerCommand {
Пожалуй базовую команду стоило оставить на верхнему уровне

2022-12-28 19:11 UTC, shining-mind commented on src/commands/layer-commands/layer-command.ts
> +  constructor(
Зря изменил базовую команду, потому что в некоторых случаях работа может идти напрямую со слоем. По-крайней мере такая задумка была. А сейчас получается, что в одном классе слишком много ответственностей (рисовать через временный слоя, через новый и т.д.). Правильнее согласно SOLID создать два отдельных класса (как было и спроектировано), где каждый отвечает за свой способ взаимодействия со слоями.

2022-12-28 19:11 UTC, shining-mind commented on src/commands/layer-commands/layer-command.ts
> +      this.layers.activeLayer.drawContents(layer);
Метод называется deleteTemporaryData при этом почему-то тут происходит рисование в активном слое. Так делать не хорошо. Стоит назвать метод, чтобы он полностью отражал суть, например: `commitTemporaryData`.

2022-12-28 19:11 UTC, shining-mind commented on src/commands/layer-commands/rect-command.ts
> +    this.context.strokeStyle = this.options.color.toString('rgb');
Такой же код есть в BrushCommand стоит сделать helper или mixin.

2022-12-28 19:11 UTC, shining-mind commented on src/commands/layer-commands/rect-command.ts
> +    console.log('layers', this.layers);
Не забудь удалить

2022-12-28 19:19 UTC, shining-mind commented on src/commands/layer-commands/layer-command.ts
> +    this.layers = layers;
Стоит подумать над тем, чтобы оформить данные код через отдельные mixin'ы

2022-12-30 00:51 UTC, shining-mind requested changes

2022-12-30 00:51 UTC, shining-mind commented on src/commands/layer-commands/rect-command.ts
> +import type { Command, CommandOptions } from '~/commands';
Эта команда должна быть в модуле ~/commands/shape-commands/

2022-12-30 00:51 UTC, shining-mind commented on src/commands/layer-commands/rect-command.ts
> +        this.#clean();
А для чего тут clean? По-моему copy должен перезатерать полностью всё что есть на слое.

2022-12-30 00:51 UTC, shining-mind commented on src/commands/layer-command.ts
> +  protected constructor(layer: Layer, iterable: AsyncIterable<Rastrr.Point>) {
Для чего тут protected?

2022-12-30 00:51 UTC, shining-mind commented on src/commands/layer-commands/brush-command.ts
> +  color: Color;
Эти свойства (color, width, lineCap) уже определены в базовом типе, их не зачем дублировать тут

2022-12-30 00:51 UTC, shining-mind commented on src/commands/layer-commands/rect-command.ts
> +  color: Color;
Эти свойства (color, width, lineCap) уже определены в базовом типе, их не зачем дублировать тут

2022-12-30 00:51 UTC, shining-mind commented on src/commands/layer-commands/rect-command.ts
> +      color: options?.color ?? new Color(0, 0, 0, 255),
not DRY, данный код дублируется в команде BrushCommand - надо сделать helper

2022-12-30 05:59 UTC, hunteraf87 commented on src/commands/layer-command.ts
> +  protected constructor(layer: Layer, iterable: AsyncIterable<Rastrr.Point>) {
Потому что класс абстрактный

2022-12-31 19:37 UTC, merged